version: "3.9"
services:
  student:
    #    container_name: student-con
    tty: true
    build:
      context: .
      target: PRODUCTION
#    volumes:
#      - .:/student:ro
    ports:
      - "7070:7070"
    environment:
      - PORT=7070
      - PHASE_TYPE=PRO
#    env_file:
#      - ./.env